pipeline {
    agent {
        kubernetes {
            label 'azcligit'
        }
    }

    environment {
        IMAGE_NAME = 'hellospring'
        ACR_NAME = 'acrrancher' // ACR 이름만 (azurecr.io 제외)
        DOCKERFILE_PATH = './app' // Dockerfile 경로
        TENANT = '7b79809c-09b9-4baa-ab98-ef8d94c6923f'
        TAG = "0.1.${BUILD_NUMBER}"
    }

    stages {
        stage('Login to Azure') {
            steps {
                container('azcligit') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'jenkins-sp',
                            usernameVariable: 'AZURE_CLIENT_ID',
                            passwordVariable: 'AZURE_CLIENT_SECRET'
                        )
                    ]) {
                        sh '''
                            az login --service-principal \
                              -u $AZURE_CLIENT_ID \
                              -p $AZURE_CLIENT_SECRET \
                              --tenant $TENANT \
                              --output none
                        '''
                    }
                }
            }
        }

        stage('Build and Push to ACR') {
            steps {
                container('azcligit') {
                    sh '''
                        az acr build \
                          --registry $ACR_NAME \
                          --image $IMAGE_NAME:$TAG \
                          $DOCKERFILE_PATH
                   '''
                }
            }
        }

        stage('Update Kustomization Tag in Git') {
            steps {
                container('azcligit') {
                    withCredentials([
                        usernamePassword(
                            credentialsId: 'git-credentials',
                            usernameVariable: 'GIT_USERNAME',
                            passwordVariable: 'GIT_PASSWORD'
                        )
                    ]) {
                        sh '''
                            git config --global user.email "tark3927@gmail.com"
                            git config --global user.name "eunyung"

                            git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/eunyung/pipelinetest.git
                            cd pipelinetest

                            sed -i 's|newTag:.*|newTag: ${TAG}|' base/kustomization.yaml

                            git commit -am "Update image tag to ${TAG}"
                            git push origin main
                        '''
                    }
                }
            }
        }
    }
}
