apiVersion: apps/v1
kind: Deployment
metadata:
 name: hellospring
 labels:
   deployment: hellospring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        deployment: hellospring
    spec:
      containers:
      - name: hellospring-container
        image: acrrancher.azurecr.io/hellospring:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
